# Cloudflare Pages configuration for Certus Frontend
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "certus-app"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"

# Note: API_BACKEND_URL is set as a secret via:
# wrangler pages secret put API_BACKEND_URL --project-name certus-admin
